version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/aws-code-build-android.jar
  discard-paths: yes
